CREATE TABLE nutritionists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    license_number VARCHAR(50) NOT NULL,
    specialty VARCHAR(255) NOT NULL,
    years_experience INTEGER NOT NULL,
    accepting_new_patients BOOLEAN,
    bio VARCHAR(1000),
    profile_picture_url VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_nutritionist_user UNIQUE (user_id)
);

CREATE TABLE nutritionist_patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nutritionist_id INTEGER NOT NULL,
    patient_user_id BIGINT NOT NULL,
    service_type VARCHAR(255) NOT NULL,
    start_date TIMESTAMP(6),
    scheduled_at TIMESTAMP(6),
    accepted BOOLEAN NOT NULL,
    requested_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_nutritionist_patient UNIQUE (nutritionist_id, patient_user_id)
);
