CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nutritionist_patient_id BIGINT NOT NULL,
    nutritionist_id INTEGER NOT NULL,
    nutritionist_user_id BIGINT NOT NULL,
    patient_user_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(255),
    notes VARCHAR(1000),
    meeting_url VARCHAR(500),
    requested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_appointments_nutritionist_scheduled_at
    ON appointments (nutritionist_user_id, scheduled_at);

CREATE INDEX idx_appointments_patient_scheduled_at
    ON appointments (patient_user_id, scheduled_at);

CREATE INDEX idx_appointments_nutritionist_patient
    ON appointments (nutritionist_patient_id);
